### PR TITLE
Deal correctly with modification 332, fix #24

### LINKED ISSUE #24: Comparison with INSEE towns file
COG file: 2016
Geohisto file: 2016

Arrondissements are ignored

```
35887 codes in Geohisto
35885 codes in COG
Town 14624 found in geohisto but not in COG: Oudon
Town 20366 found in geohisto but not in COG: Chisa
Town 27255 found in geohisto but not in COG: Fontenay
Town 28361 found in geohisto but not in COG: Saint-Symphorien-le-Château
Town 44060 found in geohisto but not in COG: Le Fresne-sur-Loire
Town 49101 found in geohisto but not in COG: Clefs
Town 52427 found in geohisto but not in COG: Robert-Magny
Town 78692 found in geohisto but not in COG: Butry-sur-Oise
Town 14472 found in COG but not in Geohisto: Oudon
Town 27693 found in COG but not in Geohisto: Sylvains-Lès-Moulins
Town 28383 found in COG but not in Geohisto: Theuville
Town 78620 found in COG but not in Geohisto: Toussus-le-Noble
Town 95120 found in COG but not in Geohisto: Butry-sur-Oise
Town 2B366 found in COG but not in Geohisto: Chisa
```

Repository: https://github.com/jdesboeufs/geohisto-compare

### PR DESCRIPTION
**Pull request by davidbgk**

### CODE REVIEW

**Comment by jdesboeufs** [comment]
2016:
```
35890 codes in Geohisto
35885 codes in COG
Town 14624 found in geohisto but not in COG: L'Oudon
Town 20366 found in geohisto but not in COG: Chisa
Town 28361 found in geohisto but not in COG: Saint-Symphorien-le-Château
Town 44060 found in geohisto but not in COG: Le Fresne-sur-Loire
Town 49101 found in geohisto but not in COG: Clefs
Town 51664 found in geohisto but not in COG: Gernicourt
Town 78692 found in geohisto but not in COG: Butry-sur-Oise
Town 95120 found in COG but not in Geohisto: Butry-sur-Oise
Town 2B366 found in COG but not in Geohisto: Chisa
```

2017:
```
35421 codes in Geohisto
35416 codes in COG
Town 14624 found in geohisto but not in COG: L'Oudon
Town 20366 found in geohisto but not in COG: Chisa
Town 28361 found in geohisto but not in COG: Saint-Symphorien-le-Château
Town 44060 found in geohisto but not in COG: Le Fresne-sur-Loire
Town 49101 found in geohisto but not in COG: Clefs
Town 78692 found in geohisto but not in COG: Butry-sur-Oise
Town 02344 found in geohisto but not in COG: Gernicourt
Town 95120 found in COG but not in Geohisto: Butry-sur-Oise
Town 2B366 found in COG but not in Geohisto: Chisa
```

**Comment by davidbgk** [comment]
@jdesboeufs I still don't get how you've got these results, see the latest line of https://raw.githubusercontent.com/etalab/geohisto/63de2134f92c33d0044c4f173efe48b23d88c48a/exports/towns/towns_2017-01-01.csv at least Chisa is good?

**Comment by davidbgk** [comment]
@jdesboeufs alright, now Chisa and Butry should be OK 😉 

Investigating the others.

**Comment by jdesboeufs** [comment]
2016:
```
35890 codes in Geohisto
35885 codes in COG
Town 14624 found in geohisto but not in COG: L'Oudon
Town 28361 found in geohisto but not in COG: Saint-Symphorien-le-Château
Town 44060 found in geohisto but not in COG: Le Fresne-sur-Loire
Town 49101 found in geohisto but not in COG: Clefs
Town 51664 found in geohisto but not in COG: Gernicourt
```

2017:
```
35421 codes in Geohisto
35416 codes in COG
Town 14624 found in geohisto but not in COG: L'Oudon
Town 28361 found in geohisto but not in COG: Saint-Symphorien-le-Château
Town 44060 found in geohisto but not in COG: Le Fresne-sur-Loire
Town 49101 found in geohisto but not in COG: Clefs
Town 02344 found in geohisto but not in COG: Gernicourt
```
🔥 🔥 🔥

**Comment by davidbgk** [comment]
So far the only remaining issue should be related to Oudon and friends 😎

**Comment by jdesboeufs** [comment]
Now I drop entries when `start_datetime` equals `end_datetime`.
But it's not trivial for end users.

2016:
```
35886 codes in Geohisto
35885 codes in COG
Town 51664 found in geohisto but not in COG: Gernicourt

$ cat data/towns_2016-01-01.csv | grep Gernicourt
COM02344@1942-01-01,02344,1942-01-01 00:00:00,2016-12-30 23:59:59,Gernicourt,COM51664@2016-12-31,,DEP02@1860-07-01,47,411
COM51664@1942-01-01,51664,1942-01-01 00:00:00,2016-12-31 23:59:59,Gernicourt,COM51171@2017-01-01,,DEP51@1860-07-01,NULL,331
```

2017:
```
35416 codes in Geohisto
35416 codes in COG
```

🎊

**Comment by davidbgk** [comment]
Actually there was still errors with Gernicourt and Le Fresne-sur-Loire even for 2017, the latest commit should fix this.

**Comment by jdesboeufs** [comment]
2016:
```
35885 codes in Geohisto
35885 codes in COG
```

2017:
```
35416 codes in Geohisto
35416 codes in COG
```

**Pull request merged**
